version: "2"
services:
  node:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
      - /run/udev:/run/udev:ro
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
      - "8001:8001"
      - "9229:9229"
    user: root
    command: bash -c "
      npm i
      && npm run start &
      bash"
